services:
  my_server:
    image: dockle:part5  # Замените на ваше имя образа и тег
    networks:
      - mynetwork  # Используем сеть для внутреннего общения

  nginx_proxy:
    image: nginx
    ports:
      - "8080:80"  # Маппинг порта контейнера nginx на порт хоста
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Подключение вашего nginx.conf
    networks:
      - mynetwork  # Используем ту же сеть для внутреннего общения
    depends_on:
      - my_server  # Указываем зависимость от первого контейнера

networks:
  mynetwork:  # Создаем собственную сеть
    driver: bridge