version: '3.9'
services:
  fcgi-server:
    build: ./fcgi-server
    container_name: fcgicontainer
    ports:
      - "8080:8080"
  nginx_proxy:
    build: ./nginx_proxy
    container_name: nginxcontainer
    ports:
      - "80:8080"